// src/pages/art/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import PageHead from '@/components/PageHead.vue'
import CoverImage from '@/components/CoverImage.vue'
import AppPagination from '@/components/AppPagination.vue'
import { artApi } from '@/api/modules'
import type { ArtListItem } from '@/api/types'
import { artCategoryLabel, heritageLabel, artImagePrompt } from '@/utils/format'
import { useLangStore } from '@/stores/lang'

const lang = useLangStore()

const CATEGORIES = [
  { value: 'music', label: '音乐' },
  { value: 'dance', label: '舞蹈' },
  { value: 'drama', label: '戏剧' },
  { value: 'costume', label: '服饰' },
  { value: 'craft', label: '手工艺' },
  { value: 'architecture', label: '建筑' },
]
const HERITAGES = [
  { value: 'world', label: '世界级' },
  { value: 'national', label: '国家级' },
  { value: 'provincial', label: '省级' },
]

const list = ref<ArtListItem[]>([])
const total = ref(0)
const page = ref(0)
const size = 12
const category = ref('')
const heritage = ref('')
const loading = ref(false)
const errored = ref(false)

async function load() {
  loading.value = true
  errored.value = false
  try {
    const res = await artApi.list({
      page: page.value,
      size,
      category: category.value || undefined,
      intangibleHeritage: heritage.value || undefined,
    })
    list.value = res.data
    total.value = res.total
  } catch {
    errored.value = true
    list.value = []
    total.value = 0
  } finally {
    loading.value = false
  }
}

function pickCategory(v: string) {
  category.value = category.value === v ? '' : v
  page.value = 0
  load()
}
function pickHeritage(v: string) {
  heritage.value = heritage.value === v ? '' : v
  page.value = 0
  load()
}
function onPage(p: number) {
  page.value = p
  load()
}

onMounted(load)
</script>

<template>
  <div class="container">
    <div class="crumb"><router-link to="/">首页</router-link> › <span>艺术</span></div>

    <PageHead
      :kicker="lang.pick('ARTS · 艺术频道', 'ARTS')"
      :title="lang.pick('传统艺术', 'Traditional Arts')"
      :dek="lang.pick('音乐、舞蹈、戏剧、手工艺与建筑——每一个民族都以自己独有的方式表达美。', 'Music, dance, drama, crafts and architecture — every group expresses beauty in its own way.')"
    />

    <div class="filter">
      <div class="row">
        <span class="label">类别</span>
        <button v-for="c in CATEGORIES" :key="c.value" class="chip" :class="{ active: category === c.value }" @click="pickCategory(c.value)">
          {{ c.label }}
        </button>
        <button v-if="category" class="chip" @click="pickCategory(category)">✕ 清除</button>
      </div>
      <div class="row">
        <span class="label">非遗级别</span>
        <button v-for="h in HERITAGES" :key="h.value" class="chip" :class="{ active: heritage === h.value }" @click="pickHeritage(h.value)">
          {{ h.label }}
        </button>
        <button v-if="heritage" class="chip" @click="pickHeritage(heritage)">✕ 清除</button>
      </div>
    </div>

    <div class="result-count">{{ lang.t('result_count', { n: total }) }}</div>

    <el-skeleton v-if="loading" :rows="6" animated />

    <div v-else-if="errored" class="ghost-block" style="text-align: center">
      <el-empty description="艺术数据加载失败">
        <el-button type="primary" @click="load">重新加载</el-button>
      </el-empty>
    </div>

    <template v-else-if="list.length">
      <div class="grid grid-3">
        <router-link v-for="a in list" :key="a.id" class="feature" :to="`/art/${a.id}`">
          <div class="img">
            <CoverImage :src="a.coverImage" :name="a.name" :prompt="artImagePrompt(a.name)" size="landscape_4_3" />
          </div>
          <div class="t">
            <span class="no">{{ artCategoryLabel[a.category] || a.category }}</span>
            <h4>{{ a.name }}</h4>
            <p>{{ a.ethnicGroupName }} · {{ heritageLabel[a.intangibleHeritage] || '' }}</p>
            <p>{{ a.description }}</p>
          </div>
        </router-link>
      </div>
      <AppPagination :current="page" :total="total" :size="size" @change="onPage" />
    </template>

    <el-empty v-else description="暂无艺术数据" style="padding: 48px 0" />
  </div>
</template>

// mobile/src/screens/art/index.tsx
import { useCallback, useEffect, useState } from 'react'
import { FlatList, StyleSheet, Text, View } from 'react-native'
import { useNavigation } from '@react-navigation/native'
import type { NativeStackNavigationProp } from '@react-navigation/native-stack'
import { Screen } from '../../components/Screen'
import ListItem from '../../components/ListItem'
import Chip from '../../components/Chip'
import EmptyView from '../../components/EmptyView'
import { artApi } from '../../api/modules'
import type { ArtListItem } from '../../api/types'
import { useLangStore } from '../../stores/lang'
import { palette, spacing, type } from '../../theme'
import type { RootStackParamList } from '../../navigation/types'

type Nav = NativeStackNavigationProp<RootStackParamList>

const CATEGORIES = [
  { value: '', label: '全部' },
  { value: 'music', label: '音乐' },
  { value: 'dance', label: '舞蹈' },
  { value: 'drama', label: '戏剧' },
  { value: 'costume', label: '服饰' },
  { value: 'craft', label: '手工艺' },
  { value: 'architecture', label: '建筑' },
]
const HERITAGES = [
  { value: '', label: '全部' },
  { value: 'world', label: '世界级' },
  { value: 'national', label: '国家级' },
  { value: 'provincial', label: '省级' },
]
const PAGE_SIZE = 20

export default function ArtScreen() {
  const navigation = useNavigation<Nav>()
  const t = useLangStore((s) => s.t)
  const pick = useLangStore((s) => s.pick)

  const [category, setCategory] = useState('')
  const [heritage, setHeritage] = useState('')
  const [list, setList] = useState<ArtListItem[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(0)
  const [loading, setLoading] = useState(false)

  const load = useCallback(
    async (pageNum: number, replace: boolean) => {
      if (loading) return
      setLoading(true)
      try {
        const res = await artApi.list({
          page: pageNum,
          size: PAGE_SIZE,
          category: category || undefined,
          intangibleHeritage: heritage || undefined,
        })
        setList((prev) => (replace ? res.data : [...prev, ...res.data]))
        setTotal(res.total)
        setPage(pageNum)
      } catch {
        // 静默
      } finally {
        setLoading(false)
      }
    },
    [loading, category, heritage]
  )

  useEffect(() => {
    setList([])
    setPage(0)
    load(0, true)
  }, [category, heritage])

  const onEnd = () => {
    if (loading || list.length >= total) return
    load(page + 1, false)
  }

  return (
    <Screen>
      <FlatList
        data={list}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <ListItem
            title={pick(item.name, item.nameEn || item.name)}
            subtitle={item.description}
            tag={item.intangible ? '非遗' : undefined}
            image={item.coverImage}
            fallbackColor={item.themeColor}
            fallbackLabel={item.name}
            onPress={() => navigation.navigate('ArtDetail', { id: item.id })}
          />
        )}
        contentContainerStyle={styles.content}
        onEndReached={onEnd}
        onEndReachedThreshold={0.3}
        ListHeaderComponent={
          <View style={styles.header}>
            <Text style={styles.title}>{t('art.title')}</Text>
            <FilterGroup label={t('art.category')} options={CATEGORIES} value={category} onChange={setCategory} />
            <FilterGroup label={t('art.heritage')} options={HERITAGES} value={heritage} onChange={setHeritage} />
          </View>
        }
        ListEmptyComponent={loading ? <EmptyView loading /> : <EmptyView />}
      />
    </Screen>
  )
}

function FilterGroup({ label, options, value, onChange }: { label: string; options: { value: string; label: string }[]; value: string; onChange: (v: string) => void }) {
  return (
    <View style={styles.group}>
      <Text style={styles.groupLabel}>{label}</Text>
      <View style={styles.chips}>
        {options.map((c) => (
          <Chip key={c.value || c.label} label={c.label} active={value === c.value} onPress={() => onChange(c.value)} />
        ))}
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  header: {
    padding: spacing.md,
    paddingBottom: spacing.sm,
  },
  title: {
    fontFamily: type.serif,
    fontSize: 28,
    color: palette.ink,
    marginBottom: spacing.md,
  },
  group: {
    marginBottom: spacing.sm,
  },
  groupLabel: {
    fontSize: 12,
    color: palette.faint,
    marginBottom: 6,
  },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingBottom: 40,
  },
})
